package it.chalmers.mufasa.android_budget_app.model;

import it.chalmers.mufasa.android_budget_app.model.database.DataAccessor;
import it.chalmers.mufasa.android_budget_app.model.database.DataAccessor.SortBy;
import it.chalmers.mufasa.android_budget_app.model.database.DataAccessor.SortByOrder;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import android.content.Context;

/*
 * A class representing a bank account.
 * 
 * @author Slurpo
 */
public class Account {

	// The id is generated by the SQLite database.
	private int id;
	private String name;
	private double balance;
	private List<Category> categoryList;
	private List<Transaction> transactionList;
	private List<BudgetItem> budgetItemList;
	private DataAccessor dataAccessor;
	private int nbrOfTransactions;

	private static Account instance = null;

	private PropertyChangeSupport pcs;

	private Account(int id, String name, Double balance, Context context) {
		setId(id);
		setName(name);
		setBalance(balance);
		dataAccessor = new DataAccessor(context, this);
		categoryList = new ArrayList<Category>();
		transactionList = new ArrayList<Transaction>();
		budgetItemList = new ArrayList<BudgetItem>();

		pcs = new PropertyChangeSupport(this);

	}

	public static Account getInstance(Context context) {
		if (instance == null) {
			instance = new Account(1, "account", 0.0, context);
		}
		return instance;
	}

	private void setId(int id) {
		this.id = id;
	}

	private void setName(String name) {
		this.name = name;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public double getBalance() {
		return dataAccessor.getAccountBalance();
	}

	public String getName() {
		return this.name;
	}

	public int getId() {
		return id;
	}

	public List<BudgetItem> getBudgetItems() {
		updateBudgetItemList();
		return budgetItemList;
	}

	private void updateBudgetItemList() {
		budgetItemList.clear();
		budgetItemList.addAll(dataAccessor.getBudgetItems());
		pcs.firePropertyChange("BudgetItems Updated", null, null);
	}

	public void addBudgetItem(Category category, Double value) {
		dataAccessor.addBudgetItem(category, value);
	}

	public void removeBudgetItem(BudgetItem budgetItem) {
		dataAccessor.removeBudgetItem(budgetItem);
	}

	public List<Category> getCategories() {
		updateCategoryList();
		return categoryList;
	}

	private void updateCategoryList() {
		categoryList.clear();
		categoryList.addAll(dataAccessor.getCategories());
		pcs.firePropertyChange("Categories Updated", null, null);

	}

	public void addCategory(String name, Category parent) {
		dataAccessor.addCategory(name, parent);
		updateCategoryList();
	}

	public void removeCategory(Category category) {
		dataAccessor.removeCategory(category);
	}

	public List<Transaction> getTransactions(int nbrOfTransactions) {
		this.nbrOfTransactions = nbrOfTransactions;
		updateTransactionList();
		return transactionList;
	}

	private void updateTransactionList() {
		transactionList.clear();
		transactionList.addAll(dataAccessor.getTransactions(this, SortBy.DATE,
				SortByOrder.DESC, 0, nbrOfTransactions));
		pcs.firePropertyChange("Transactions Updated", null, null);
	}

	public void addTransaction(double amount, Date date, String name,
			Category category) {
		dataAccessor.addTransaction(amount, date, name, category);
	}

	public void removeTransaction(Transaction transaction) {
		dataAccessor.removeTransaction(transaction);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(balance);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + id;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Account other = (Account) obj;
		if (Double.doubleToLongBits(balance) != Double
				.doubleToLongBits(other.balance)) {
			return false;
		}
		if (id != other.id) {
			return false;
		}
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}

	public void addPropertyChangeListener(PropertyChangeListener l) {
		pcs.addPropertyChangeListener(l);
	}

	public void removePropertyChangeListener(PropertyChangeListener l) {
		pcs.removePropertyChangeListener(l);
	}

}
